name: Fly Deploy to the dev page

on:
  push:
    branches: [ dev ]
  pull_request:
    branches: [ dev ]
    
jobs:
  setup:
    name: Setup Backend, Build Frontend and Run Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: frontend

      - name: Run Unit Tests
        run: npm run test:unit
        working-directory: frontend

      - name: Build Frontend (Development)
        run: npm run build:localdev
        working-directory: frontend

      - name: Install Backend Dependencies
        run: npm ci
        working-directory: backend

      - name: Copy secrets to .env file
        env:
          BREVO_API_KEY: ${{ secrets.BREVO_API_KEY }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          DATABASE_TOKEN_DEV: ${{ secrets.DATABASE_TOKEN_DEV }}
        run: |
          cd backend
          echo "JWT_SECRET=$JWT_SECRET" > .env
          echo "DATABASE_URL=libsql://bookworms-dev-szankdav.turso.io
          DATABASE_TOKEN=$DATABASE_TOKEN_DEV
          PAGE_URL=https://bookworms-dev.fly.dev/" > .env.development
          cat .env.development

      - name: Start Backend Server
        run: npm run start:dev &
        working-directory: backend

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
        working-directory: frontend 

      - name: Run Playwright Tests
        run: npm run test:e2e:localdev
        working-directory: frontend

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: frontend/playwright-report/
          retention-days: 30

  deploy:
    name: Deploy Backend Server
    runs-on: ubuntu-latest
    needs: [setup]  # Ensures 'deploy' job runs after 'setup' and 'test' jobs
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Frontend Dependencies
        run: npm ci
        working-directory: frontend

      - name: Build Frontend (Development)
        run: npm run build:dev
        working-directory: frontend

      - name: Set up Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Deploy Backend
        run: |
          cd backend
          flyctl deploy -c fly.dev.toml --no-cache
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}